wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.5
batch_size:
  desc: null
  value: 100
buckets:
  desc: null
  value: 20
epochs:
  desc: null
  value: 1000
max_len:
  desc: null
  value: 11
